// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using garden_planner.Data;

#nullable disable

namespace garden_planner.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220717073853_SeedDataMigration")]
    partial class SeedDataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("garden_planner.Data.PlantVariety", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Autum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Spring")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Summer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sun")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Water")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Winter")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("PlantVarieties");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Autum = false,
                            Description = "basil, (Ocimum basilicum), also called sweet basil, annual herb of the mint family ",
                            Image = "basil.svg",
                            Lifecycle = "Annual",
                            Name = "Basil",
                            Spring = true,
                            Summer = true,
                            Sun = "Full",
                            Water = "High",
                            Winter = false
                        },
                        new
                        {
                            ID = 2,
                            Autum = false,
                            Description = "The leaves are used fresh or dried to flavour meats, fish, salads, and sauces",
                            Image = "basil.svg",
                            Lifecycle = "Annual",
                            Name = "Basil",
                            Spring = true,
                            Summer = true,
                            Sun = "Full",
                            Water = "High",
                            Winter = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
